name: aoc-ci

on:
  push:
    branches: [ "main", "ci" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      # https://github.com/gradle/gradle-build-action
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      # https://github.com/gradle/gradle-build-action
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: ktlintCheck
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true